services:
  db:
    container_name: postgres_aiogram
    image: postgres
    environment:
      POSTGRES_PASSWORD: 'db_password'
    ports:
      - 5433:5432
    restart: always
    networks:
      - botnet

  app:
    build: .
    container_name: sync-bot-server
    command: python app.py
    restart: always
    volumes:
      - .:/app
    networks:
      - botnet
    depends_on:
      - db

networks:
  botnet:
    driver: bridge
